name: Deploy para Páginas do GitHub

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checar o repositório
        uses: actions/checkout@v3

      - name: Configurar o GitHub Pages
        uses: actions/configure-pages@v3

      - name: Criar os arquivos para deploy
        uses: actions/upload-pages-artifact@v3
        with:
          path: .  # Aqui ele pega todos os arquivos da raiz do repositório

      - name: Publicar no GitHub Pages
        uses: actions/deploy-pages@v3  # Usando a versão mais recente
