name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build project
        run: |
          npm install
          npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v3  # Corrected version to v3
        with:
          name: build-output
          path: ./build

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download build artifact
        uses: actions/download-artifact@v3  # Ensure this is the correct version
        with:
          name: build-output

      - name: Deploy to GitHub Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./build
